name: Terraform Deploy or Destroy

on:
  workflow_dispatch:
    inputs:
      customer:
        description: 'Select customer'
        required: true
        type: choice
        options:
          - hyc
          - stttelemedia
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - dev
          - prod
      action:
        description: 'Terraform Action'
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          audience: api://AzureADTokenExchange

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -input=false

      - name: Select or Create Workspace
        run: |
          WORKSPACE="${{ github.event.inputs.customer }}-${{ github.event.inputs.environment }}"
          if terraform workspace list | grep -q "$WORKSPACE"; then
            terraform workspace select "$WORKSPACE"
          else
            terraform workspace new "$WORKSPACE"
          fi

      - name: Terraform Plan or Destroy
        run: |
          ACTION=${{ github.event.inputs.action }}
          TFVARS="customer/${{ github.event.inputs.customer }}.tfvars"

          if [ "$ACTION" == "apply" ]; then
            terraform plan -input=false -var-file="$TFVARS" -out=tfplan
          else
            terraform plan -destroy -input=false -var-file="$TFVARS" -out=tfplan
          fi
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: "true"

      - name: Terraform Apply or Destroy
        run: terraform apply -input=false -auto-approve tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: "true"
