name: Terraform Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow with OIDC & Approval
    runs-on: ubuntu-latest
    environment:
      name: production

    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          audience: api://AzureADTokenExchange  # Required for OIDC

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Create apps.tfvars file
        run: |
          cat > apps.tfvars <<EOF
          client_id       = "${{ secrets.ARM_CLIENT_ID }}"
          tenant_id       = "${{ secrets.ARM_TENANT_ID }}"
          subscription_id = "${{ secrets.ARM_SUBSCRIPTION_ID }}"
          use_oidc        = true
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Select or Create Workspace
        run: terraform workspace select production -or-create

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var-file="apps.tfvars" -out=tfplan

      - name: Manual Approval Before Apply
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: lunar-gultom
          minimum-approvals: 1
          issue-title: "Terraform Apply Approval"
          issue-body: "Approve to apply Terraform changes to Azure."
          label: "terraform-apply"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan