on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow with OIDC & Approval
    runs-on: ubuntu-latest
    environment:
      name: production

    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          audience: api://AzureADTokenExchange

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -input=false

      - name: Handle Workspace
        run: |
          if terraform workspace list | grep -q 'production'; then
            terraform workspace select production
          else
            terraform workspace new production
          fi

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -var-file="apps.tfvars" \
            -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
            -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
            -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -var="use_oidc=true" \
            -out=tfplan
          
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: "true"
          
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: "true"