name: Terraform Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow with OIDC & Approval
    runs-on: ubuntu-latest
    environment:
      name: production

    permissions:
      id-token: write        # Required for OIDC login
      contents: read         # Required to clone repo

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          audience: api://AzureADTokenExchange

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select production || terraform workspace new production

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Manual Approval Before Apply
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: lunar-gultom
          minimum-approvals: 1
          issue-title: "Terraform Apply Approval"
          issue-body: "Approve to apply Terraform changes to Azure."
          label: "terraform-apply"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
